{{- if .Values.env.GEMINI_API_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sag-rag.fullname" . }}-gemini
type: Opaque
stringData:
  GEMINI_API_KEY: "{{ .Values.env.GEMINI_API_KEY }}"
{{- end }}
